### ISSUE TITLE
Hard to see selection color

### ISSUE THREAD

**Issue by tobias-tengler** [EliverLara/sweet-vscode#1]
First of all, thank you for this amazing theme! :)
I know it's just a couple minutes after the first release of this theme, but this is something I immediately noticed: The `editor.selectionBackground` color is really hard to see.

![Demonstration](https://user-images.githubusercontent.com/45513122/75614275-5116d080-5b37-11ea-9533-03ad17c58332.png)

Please consider changing it to something that contrasts a little better with the background.
Other than that great work - I'm absolutely in love with your sweet theme 'series'! <3

_Something different: What's the name of the VS Code directory and file icons package, you used in your screenshot in the README?_

**Comment by EliverLara** [comment]
Hi, I have changed the selection color for a more contrasted one, I think it looks better now.
The file icons shown in screenshot [are these](https://github.com/cdonohue/vscode-quill-icons) with some little modifications.

**Comment by tobias-tengler** [comment]
Yes, definitely a lot better to work with. :) 
Just set `selection.background` to the new selection color as well, so it's also applied to other text selections, like in dialogs, search bars, etc.
Feel free to close this issue, once you published a new version containing the changes and thanks again for this amazing theme!

**Comment by st-schneider** [comment]
Can you add the icons to the theme?

**Comment by EliverLara** [comment]
Done!
