### ISSUE TITLE
Not available in vscodium by default

### ISSUE THREAD

**Issue by roudra-das** [EliverLara/sweet-vscode#10]
I love the sweet themes you make but it is not currently available on vscodium by default. 
Would you consider publishing it to the Open VSX Registry?

**Comment by Alex-Anev** [comment]
pls

**Comment by stepanzak** [comment]
please do it 🙏🙏🙏

**Comment by Kevadroz** [comment]
+1

**Comment by Letgamer** [comment]
I added sweet-vscode and sweet-vscode-icons to Open-VSX, so they are now both available in VSCodium, feel free to check it out!
https://open-vsx.org/extension/Letgamer/sweet-vscode-icons
https://open-vsx.org/extension/Letgamer/sweet-vscode
https://github.com/Letgamer/sweet-vscode
https://github.com/Letgamer/sweet-vscode-icons
@stepanzak @roudra-das @Alex-Anev @forlornidealist @HugoGranstrom @Kevadroz
