### ISSUE TITLE
Unreadable text/icons on the left side

### ISSUE THREAD

**Issue by ShayBox** [EliverLara/sweet-vscode#3]
The text/icons are too similar to the background, maybe it's my vision or my monitor but its too difficult to read.
![image](https://user-images.githubusercontent.com/9505196/76674645-23df0f00-6588-11ea-8a1e-da824e352ad0.png)

**Comment by didinele** [comment]
Adding to the general text color, while code itself looks fine and in fact, I, personally, absolutely love it, strings are a little bit too dark.

**Comment by EliverLara** [comment]
It is more contrasted in the new version that has just been released.

**Comment by KBeDevel** [comment]
Which property is used to edit these colors?
