### ISSUE TITLE
re; icons

### ISSUE THREAD

**Issue by didinele** [EliverLara/sweet-vscode#4]
Hi! Both your reddit post and the screenshot provided on the repo contain an icon theme.

This repo does not currently include those and neither does the theme itself.

Is this a WIP or did you acidentally forget to push them?

**Comment by EliverLara** [comment]
Hi, you can find the vscode icons [here](https://github.com/EliverLara/sweet-vscode-icons).

**Comment by didinele** [comment]
Ah, my bad, thanks a bunch.
