### ISSUE TITLE
Comments are too dark to see

### ISSUE THREAD

**Issue by KBeDevel** [EliverLara/sweet-vscode#5]
![image](https://user-images.githubusercontent.com/28226964/78090031-6897e200-739f-11ea-9f03-bb500e4fd017.png)
In all languages I tested (TypeScript (/**/, //), Python (#) & Haskell (--) at least) comments are too dark (and hard) to see :c 

[UPDATE] This should be considered, specially, for people who don't use bold fonts

**Comment by KBeDevel** [comment]
I'm thinking in `#d8d7d0` or `#a1a09b`

**Comment by EliverLara** [comment]
Now they are more visible:

Before | After
--- | ---
![before](https://user-images.githubusercontent.com/9838260/78508032-73f55f80-7749-11ea-80c1-d9a4a6f36bb6.png) | ![after](https://user-images.githubusercontent.com/9838260/78508036-7952aa00-7749-11ea-9c59-5d061c181d07.png)

**Comment by KBeDevel** [comment]
Nice!
